### PR TITLE
fixed main file

### PR DESCRIPTION
**Pull request by faluhub**

### CODE REVIEW

**Review by dev-viinz — APPROVED** [review]

**Review by dev-viinz — CHANGES_REQUESTED** [review]
probably meant to say `self.cog_blacklist` there? 
```suggestion
        self.cog_blacklist = [
        "__init__.py", "functions.py"
        ]
```

**Comment by faluhub** [comment]
> probably meant to say `self.cog_blacklist` there?
> 
> ```
>         self.cog_blacklist = [
>         "__init__.py", "functions.py"
>         ]
> ```

thats exactly what it says?

**Comment by faluhub** [comment]
fixed lmfao sorry i didnt see

**Comment by dev-viinz** [comment]
Why exactly do you think this should be added? It doesn't add any functionality (other than intents), and doesn't significantly boost performance. We could consider an addition to the code base if it actually changed something.
(Don't get me wrong, making it more object oriented isn't necessarily a bad idea, but there is just no good reason for it.

Again, nothing wrong with your code.

**Pull request closed without merging**
